stages: 
  - build
  - test

build front:
  image: node:16-alpine
  stage: build
  script:
    - yarn install
    - yarn build
    - echo "check index.html"
  artifacts:
    paths:
      - build

test front:
  image: node:16-alpine
  stage: test
  script:
    - test -f build/index.html
    - yarn global add serve
    - apk add curl
    - serve -s build &
    - sleep 10
    - curl http://localhost:3000 | grep "Learn react"

unit test:
  image: node:16-alpine
  stage: test
  script:
    - yarn install
    - yarn test
