stages: 
  - build
  - test
  - deploy

build front:
  image: node:16-alpine
  stage: build
  script:
    - yarn install
    - yarn build
    - echo "check index.html"
  artifacts:
    paths:
      - build

test front:
  image: node:16-alpine
  stage: test
  script:
    - test -f build/index.html
    - yarn global add serve
    - apk add curl
    - serve -s build &
    - sleep 10
    - curl http://localhost:8080 | grep "Learn react"

deploy to s3:
  stage: deploy
  image: 
    name: amazon/aws-cli:2.4.11
    entrypoint: [""]
  script:
    - aws --version
    - echo "Hello S3" > test.txt
    - aws s3 sync build s3://$AWS_S3_BUCKET --delete
